version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
  test:
    steps:
      - run:
          name: Testing application
          command: echo Test Start.
          shell: /bin/bash
          environment:
            FOO: bar

  deploy:
    steps:
      - run: 
          name: Deploy application
          command: echo Deploy Application.


workflows:
  version: 2
  job-and-job:
    jobs:   
      - build:
          filters:
            branches:
              only:
                - master
                - /^feature/test-.*/
                - /^develop/test-.*/
                - /^hotfix/test-.*/
      - test:
          requires:
            - build
      - hold:
          type: approval
          filters:
            branches:
              only:
                - master
                - /^feature/test-.*/
          requires:
            - build
            - test
      - deploy:
          filters:
            branches:
              only:
                - master
                - /^feature/test-.*/
          requires:
            - build
            - test
            - hold
